package com.asimio.dvdrental.model;
// Generated Jul 21, 2016 11:52:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ActorInfo generated by hbm2java
 */
@Entity
@Table(name="actor_info"
    ,schema="public"
)
public class ActorInfo  implements java.io.Serializable {


     private ActorInfoId id;

    public ActorInfo() {
    }

    public ActorInfo(ActorInfoId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="actorId", column=@Column(name="actor_id") ), 
        @AttributeOverride(name="firstName", column=@Column(name="first_name", length=45) ), 
        @AttributeOverride(name="lastName", column=@Column(name="last_name", length=45) ), 
        @AttributeOverride(name="filmInfo", column=@Column(name="film_info") ) } )
    public ActorInfoId getId() {
        return this.id;
    }
    
    public void setId(ActorInfoId id) {
        this.id = id;
    }




}


